// ─── Shared Types ───────────────────────────────────────────────────────────

/** Supported package ecosystems */
export type Ecosystem = "npm" | "maven" | "pypi" | "cargo" | "go" | "nuget";

/** A single parsed dependency from a manifest file */
export interface ParsedDependency {
  name: string;
  version: string;
  ecosystem: Ecosystem;
  isDev: boolean;
  manifestPath: string;
}

/** A manifest file fetched from a repository */
export interface ManifestFile {
  path: string;
  content: string;
  ecosystem: Ecosystem;
}

/** Severity level for vulnerabilities */
export type Severity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "UNKNOWN";

/** Unified vulnerability record from any source */
export interface UnifiedVulnerability {
  cveId: string | null;
  osvId?: string;
  githubAdvisoryId?: string;
  severity: Severity;
  cvssScore: number | null;
  cvssVector: string | null;
  summary: string;
  details: string | null;
  publishedDate: string | null;
  modifiedDate: string | null;
  fixedVersions: string[];
  references: string[];
  source: "OSV" | "NVD" | "GITHUB" | "CISA_KEV";
  affectedRange: string | null;
  /** Is this CVE in the CISA Known Exploited Vulnerabilities catalog? */
  kev: boolean;
  /** Structured mitigation guidance if available */
  mitigationGuidance: string | null;
}

/** Result of scanning a single dependency */
export interface DependencyScanResult {
  dependency: ParsedDependency;
  vulnerabilities: UnifiedVulnerability[];
}

/** Complete scan report */
export interface ScanReport {
  scanId: string;
  repoUrl: string;
  repoOwner: string;
  repoName: string;
  scannedAt: string;
  totalDependencies: number;
  totalVulnerabilities: number;
  severityCounts: Record<Severity, number>;
  results: DependencyScanResult[];
}

// ─── Parser Interface ───────────────────────────────────────────────────────

/** Interface that all manifest parsers must implement */
export interface ManifestParser {
  /** The ecosystem this parser handles */
  ecosystem: Ecosystem;

  /** Filenames this parser can handle */
  supportedFiles: string[];

  /** Check if this parser can handle a given filename */
  canParse(filename: string): boolean;

  /** Parse file content and return list of dependencies */
  parse(content: string, filepath: string): ParsedDependency[];
}

// ─── Vulnerability DB Client Interface ──────────────────────────────────────

/** Interface for vulnerability database clients */
export interface VulnDBClient {
  /** Name of the data source */
  source: "OSV" | "NVD" | "GITHUB" | "CISA_KEV";

  /** Query vulnerabilities for a specific package */
  query(
    ecosystem: Ecosystem,
    packageName: string,
    version: string
  ): Promise<UnifiedVulnerability[]>;
}

// ─── Repository Understanding Types ─────────────────────────────────────────

/** Structured metadata extracted from a repository */
export interface RepositoryMetadata {
  language: string | null;
  languages: Record<string, number>;
  framework: string | null;
  purpose: string | null;
  topics: string[];
  description: string | null;
  folderHierarchy: FolderNode[];
  totalFiles: number;
  hasDockerfile: boolean;
  hasCiCd: boolean;
  hasTests: boolean;
  stars: number;
  forks: number;
  openIssues: number;
  lastPushed: string | null;
}

/**
 * Extended repository profile generated by deep structural analysis.
 * Extends RepositoryMetadata with architecture and deployment signals.
 * This is the "global context" object passed to every downstream module.
 */
export interface RepositoryProfile extends RepositoryMetadata {
  /** Detected architecture pattern (e.g. MVC, microservices, monolith, layered) */
  architecture: string | null;
  /** Repository type classification */
  repositoryType: "web-app" | "api" | "library" | "cli" | "monorepo" | "data" | "unknown";
  /** Detected database technology (e.g. postgres, mongodb, mysql, redis) */
  database: string | null;
  /** Detected ORM or query builder (e.g. prisma, sequelize, mongoose, sqlalchemy) */
  orm: string | null;
  /** Detected authentication mechanism (e.g. jwt, oauth2, session, passport) */
  authentication: string | null;
  /** Detected deployment platform (e.g. docker, kubernetes, heroku, vercel, aws) */
  deployment: string | null;
  /** Detected CI/CD platform (e.g. github-actions, gitlab-ci, jenkins, circleci) */
  ciCdPlatform: string | null;
  /** Detected testing framework (e.g. jest, vitest, mocha, pytest, junit) */
  testingFramework: string | null;
  /** Detected package managers in use */
  packageManagers: string[];
  /** Names of primary runtime dependencies (not devDeps) */
  primaryDependencies: string[];
}

/** A node in the folder hierarchy */
export interface FolderNode {
  path: string;
  type: "blob" | "tree";
  size?: number;
}

// ─── Repository Knowledge Graph (RKG) Types ───────────────────────────────────

export type RKGNodeType = "Repository" | "File" | "Module" | "Dependency" | "Package" | "Threat";
export type RKGEdgeType =
  | "CONTAINS"
  | "IMPORTS"
  | "DEPENDS_ON"
  | "AFFECTS"
  | "REMEDIATES"
  // Enrichment edges (Phase 2 — threat intelligence layer)
  | "HAS_CVSS"
  | "IN_KEV"
  | "FIXED_BY"
  | "REPLACED_BY";

export interface RKGNode {
  id: string;
  label: string;
  type: RKGNodeType;
  properties: Record<string, unknown>;
}

export interface RKGEdge {
  source: string;
  target: string;
  relationship: RKGEdgeType;
  weight?: number;
}

export interface RepositoryKnowledgeGraph {
  nodes: RKGNode[];
  edges: RKGEdge[];
}

/** Traversal path through the enriched graph */
export interface GraphContextPath {
  dependency: string;
  package: string;
  threatId: string | null;
  affectedModules: string[];
  impactedFiles: string[];
  /** Patch versions from FIXED_BY enrichment nodes */
  patchVersions: string[];
  /** Whether this CVE is in the CISA KEV catalog (from IN_KEV edge) */
  kevStatus: boolean;
  explanation: string;
}

// ─── Chunking & Hybrid Retrieval Types ────────────────────────────────────────

/** Type of a repository chunk */
export type ChunkType = "function" | "class" | "module" | "documentation" | "config";

/** A semantic chunk of repository code or documentation */
export interface RepoChunk {
  filePath: string;
  chunkType: ChunkType;
  language: string | null;
  content: string;
  startLine: number | null;
  endLine: number | null;
  /** Embedding vector (768-dim for text-embedding-004) */
  embedding?: number[];
}

/** A chunk retrieved from the hybrid search engine */
export interface RetrievedChunk extends RepoChunk {
  id: string;
  similarityScore: number;
  denseScore?: number;
  bm25Score?: number;
  rrfScore?: number;
}

/**
 * Explicit filter criteria for hybrid BM25+Dense retrieval.
 * Each field is independently composable (all optional, ANDed together).
 */
export interface RetrievalFilter {
  /** Filter by programming language (e.g. ["typescript", "python"]) */
  languages?: string[];
  /** Filter by detected framework (e.g. ["express", "django"]) — matched against file path heuristics */
  frameworks?: string[];
  /** Filter by specific dependency name — retrieves only chunks from files that import this package */
  dependencyNames?: string[];
  /** Filter by chunk semantic type */
  chunkTypes?: ChunkType[];
  /** Filter by exact file paths */
  filePaths?: string[];
}

// ─── Similar Repository Health Signal Types ───────────────────────────────────

export type MaintenanceActivity = "active" | "moderate" | "stale";

/** A semantically similar public GitHub repository with rich health signals */
export interface SimilarRepo {
  owner: string;
  repo: string;
  fullName: string;
  description: string | null;
  language: string | null;
  stars: number;
  forks: number;
  openIssues: number;
  pushAgeDays: number;
  maintenanceActivity: MaintenanceActivity;
  healthScore: number; // 0-100 score based on stars, push age, issue activity
  topics: string[];
  similarityScore: number;
  githubUrl: string;
}

/**
 * Evidence collected from a similar repository for a specific dependency.
 * Allows reasoning engine to cite "Repository X uses express@4.18.3 successfully".
 */
export interface SimilarRepoEvidence {
  /** The similar repository this evidence comes from */
  repoFullName: string;
  repoUrl: string;
  similarityScore: number;
  healthScore: number;
  maintenanceActivity: MaintenanceActivity;
  /** Dependencies this repo shares with the scanned repo */
  sharedDependencies: string[];
  /** If a known-safe version of the vulnerable dep is used, record it */
  knownSafeVersion: string | null;
  /** e.g. "Uses express@4.18.3 (patched) — upgraded from 4.16.x" */
  upgradePattern: string | null;
}

/**
 * Unified context object constructed before invoking the reasoning engine.
 * Every field flows from a previous pipeline stage — nothing is re-fetched.
 * This is the single source of truth for LLM context construction.
 */
export interface RepositoryContext {
  /** From RepoUnderstander — the full structural profile */
  profile: RepositoryProfile | null;
  /** From knowledge graph — text summary of graph structure */
  graphSummary: string;
  /** From knowledge graph traversal — per-package impact paths */
  graphPaths: GraphContextPath[];
  /** From ContextRetriever — top-K semantically relevant code chunks */
  retrievedChunks: RetrievedChunk[];
  /** From SimilarRepoFinder — repos ranked by relevance */
  similarRepos: SimilarRepo[];
  /** From SimilarRepoFinder — per-package evidence from similar repos */
  similarRepoEvidence: SimilarRepoEvidence[];
  /** From VulnerabilityScanner — threat intelligence summary */
  threatSummary: string;
  /** Provider used for reasoning (populated after LLM call) */
  providerUsed?: string;
}

/**
 * Human-readable summary of the full intelligence pipeline results.
 * Included in the final AnalysisResult for report generation.
 */
export interface IntelligenceSummary {
  /** What was understood about the repository */
  repositoryUnderstanding: string;
  /** Detected technology stack as a brief description */
  stackDescription: string;
  /** Knowledge graph statistics */
  graphStats: {
    totalNodes: number;
    totalEdges: number;
    fileCount: number;
    moduleCount: number;
    packageCount: number;
    threatCount: number;
    kevCount: number;
  };
  /** How similar repos influenced decisions */
  similarRepoInfluence: string;
  /** Threat intelligence summary */
  threatIntelSummary: string;
  /** Projected RSIS score after all recommended remediations applied */
  projectedRsisAfterRemediation: number;
}

// ─── Remediation, Reasoning & Ranking Types ───────────────────────────────────

/** Possible remediation action types */
export type RemediationAction = "upgrade" | "replace" | "mitigate" | "accept";

/** Compatibility risk level */
export type CompatibilityRisk = "low" | "medium" | "high";

/** Step in a chain of reasoning */
export interface ChainStep {
  stepNumber: number;
  observation: string;
  deduction: string;
}

/** Explicit code evidence reference grounding a recommendation */
export interface EvidenceReference {
  filePath: string;
  startLine?: number | null;
  endLine?: number | null;
  codeSnippet?: string;
  relevance: string;
}

/** Multi-feature score breakdown for ranking candidate patches */
export interface CandidateRankingFeatures {
  compatibilityScore: number;    // 0-1 (SemVer patch/minor/major delta)
  securityGainScore: number;     // 0-1 (CVSS score reduction + KEV resolution)
  dependencyImpactScore: number; // 0-1 (inverse of transitive dependency risk)
  validationScore: number;       // 0-1 (registry existence + OSV re-scan result)
  patternAlignmentScore: number; // 0-1 (healthy similar repo adoption signals)
  /**
   * Evidence Strength Score (0-1): measures how many independent threat intel
   * sources corroborate this candidate.
   * Score formula: each source adds weight:
   *   OSV=0.20, NVD=0.20, GitHub Advisory=0.25, CISA KEV=0.20, Similar Repo=0.15
   * A candidate backed by all 5 sources scores 1.0.
   * A pure-LLM candidate with no external validation scores 0.15.
   */
  evidenceStrengthScore: number;
  utilityScore: number;          // Weighted composite ranking score
}

/** A single candidate patch recommendation */
export interface RemediationCandidate {
  action: RemediationAction;
  explanation: string;
  reasoning: string;
  chainOfReasoning?: ChainStep[];
  evidence?: EvidenceReference[];
  confidence: number;           // 0–1
  compatibilityRisk: CompatibilityRisk;
  proposedVersion: string | null;
  alternativePackage: string | null;
  dependencyImpact: string[];   // list of transitively affected packages
  validated: boolean;
  rejected: boolean;
  rejectionReason: string | null;
  validationNotes: string | null;
  rankingFeatures?: CandidateRankingFeatures;
  rank?: number;
}

/** The full remediation report for a vulnerability in a scan */
export interface RemediationReport {
  scanId: string;
  cveId: string | null;
  packageName: string;
  ecosystem: Ecosystem;
  candidates: RemediationCandidate[];
  reasoningTrace: string | null;
  contextChunks: RetrievedChunk[];
  graphContext?: GraphContextPath[];
  validationPassed: boolean;
}

// ─── RSIS Score Types ────────────────────────────────────────────────────────

/** Configurable weights for RSIS score components (Sum = 1.0) */
export interface RSISWeights {
  security: number;        // w1 (Default: 0.30)
  retrieval: number;       // w2 (Default: 0.20)
  validation: number;      // w3 (Default: 0.20)
  maintainability: number; // w4 (Default: 0.15)
  compatibility: number;   // w5 (Default: 0.15)
}

/** Raw measurable signals used to compute RSIS */
export interface RSISSignals {
  criticalVulns: number;
  highVulns: number;
  mediumVulns: number;
  lowVulns: number;
  totalVulns: number;
  totalDeps: number;
  highConfidenceCandidates: number;
  totalCandidates: number;
  meanRetrievalSimilarity: number;
  hybridMRR: number;
  validatedCandidates: number;
  totalValidated: number;
  recentDeps: number;
  kevCount: number;
  semverCompatRate: number; // % of proposed upgrades within same major version
}

/** Rationale & literature citations for RSIS weights */
export interface RSISLiteratureRationale {
  formula: string;
  citations: string[];
  ablationNotes: string;
}

/** Full RSIS score with breakdown */
export interface RSISScore {
  totalScore: number;
  securityScore: number;       // Formerly severityScore
  retrievalScore: number;
  validationScore: number;
  maintainabilityScore: number;
  compatibilityScore: number;  // New explicit dimension
  weights: RSISWeights;
  signals: RSISSignals;
  rationale: RSISLiteratureRationale;
  grade: "A" | "B" | "C" | "D" | "F";
}

// ─── ML Evaluation Types ──────────────────────────────────────────────────────

/** Retrieval evaluation metrics */
export interface RetrievalMetrics {
  precisionAtK: number;
  recallAtK: number;
  mrr: number;
  ndcg: number;
  k: number;
}

/** Patch recommendation evaluation metrics */
export interface RecommendationMetrics {
  top1Accuracy: number;
  top3Accuracy: number;
}

/** Validation pipeline evaluation metrics */
export interface ValidationMetrics {
  buildSuccessRate: number;
  vulnReductionRate: number;
}

/** Complete set of ML evaluation metrics for a scan */
export interface EvalMetrics {
  retrieval: RetrievalMetrics;
  recommendation: RecommendationMetrics;
  validation: ValidationMetrics;
}

// ─── Full Analysis Result ─────────────────────────────────────────────────────

/** The complete result from the full intelligence pipeline */
export interface AnalysisResult {
  scanId: string;
  scan: ScanReport;
  /** Legacy field — use repositoryProfile for full stack detection */
  metadata: RepositoryMetadata | null;
  /** Full structured profile with architecture, deployment, ORM, auth signals */
  repositoryProfile: RepositoryProfile | null;
  knowledgeGraph: RepositoryKnowledgeGraph;
  chunksIndexed: number;
  similarRepos: SimilarRepo[];
  remediations: RemediationReport[];
  rsis: RSISScore;
  /** Intelligence pipeline summary — used for report generation */
  intelligenceSummary: IntelligenceSummary | null;
  aiEnabled: boolean;
}
